#(attack,weakness,percentage)
#1
weakness(forced_deadlock,unrestricted_externally_accessible_lock,1).
weakness(forced_deadlock,unsynchronized_access_to_shared_data_in_a_multithreaded_context,1).
weakness(forced_deadlock,improper_locking,1). 
weakness(forced_deadlock,deadlock,1).
weakness(forced_deadlock,use_of_blocking_code_in_single_threaded,_non_blocking_context,1).



#2
weakness(leveraging_race_condition_via_symbolic_links,time_of_check_time_of_use_race_condition,1).
weakness(leveraging_race_condition_via_symbolic_links,unix_symbolic_link_following,1).
weakness(leveraging_race_condition_via_symbolic_links,improper_synchronization,1).
weakness(leveraging_race_condition_via_symbolic_links,permission_race_condition_during_resource_copy,1).
weakness(leveraging_race_condition_via_symbolic_links,improper_locking,1).



#3
weakness(bypassing_of_intermediate_forms_in_multiple_form_sets,incomplete_internal_state_distinction,1).