% mitigation(attack,mitigation,percentage)

% employ probabilistic techniques
mitigation(fuzzing_for_application_mapping,obfuscate_server_fields_of_http_response,80).
mitigation(fuzzing_for_application_mapping,hide_inner_ordering_of_http_response_header,75).
mitigation(fuzzing_for_application_mapping,customizing_http_error_codes,75).
mitigation(fuzzing_for_application_mapping,hide_http_response_information,40).
mitigation(fuzzing_for_application_mapping,hide_cookies,40).

mitigation(encryption_brute_forcing,use_commonly_accepted_algorithms,70).
mitigation(encryption_brute_forcing,moore's_law,90).

mitigation(dictionary-based_password_attack,create_strong_passwords,85).
mitigation(dictionary-based_password_attack,implement_intelligent_password_throttling_mechanism,85).
mitigation(dictionary-based_password_attack,multi_factor_authentication,95).

mitigation(rainbow_table_password_cracking,use_salt_when_hashing_passwords,72).

mitigation(password_spraying,create_strong_passwords,80).
mitigation(password_spraying,implement_intelligent_password_throttling_mechanism,85).
mitigation(password_spraying,multi_factor_authentication,95).

mitigation(try_common_or_default_usernames_and_passwords,delete_default_account_credentials,88).
mitigation(try_common_or_default_usernames_and_passwords,implement_intelligent_password_throttling_mechanism,85).
mitigation(try_common_or_default_usernames_and_passwords,create_strong_passwords,85).
mitigation(try_common_or_default_usernames_and_passwords,password_recycling,85).

% subvert access control

mitigation(cross_zone_scripting,disable_script_execution,96).
mitigation(cross_zone_scripting,input_validation,79).
mitigation(cross_zone_scripting,ensure_proper_html_output,85).

mitigation(catching_exception_throw_signal_from_privileged_block,careful_desing_of_callback_signal_and_other_asynchronous_constructs,70).
mitigation(catching_exception_throw_signal_from_privileged_block,careful_desing_of_privileged_code_blocks,70).

mitigation(target_programs_with_elevated_privileges,principle_of_least_privilege,85).
mitigation(target_programs_with_elevated_privileges,validate_untrusted_data,85).
mitigation(target_programs_with_elevated_privileges,apply_latest_patches,90).
mitigation(target_programs_with_elevated_privileges,protect_logs_from_log_forging,90).
mitigation(target_programs_with_elevated_privileges,traffic_and_resource_usage_monitoring,75).

mitigation(restful_privilege_elevation,ensure_get_methods_only_retrieve_state,85).

mitigation(modify_shared_file,disallow_shared_content,100).
mitigation(modify_shared_file,minimize_users_with_shared_access,70).

mitigation(add_malicious_file_to_shared_webroot,ensure_permission_on_accessible_directories,80).
mitigation(add_malicious_file_to_shared_webroot,disallow_remote_access,100).
mitigation(add_malicious_file_to_shared_webroot,disable_execution_on_directories_withing_web_root,100).

mitigation(replace_binaries,ensure_commonly_used_binaries_have_correct_permission,85).
mitigation(replace_binaries,restrict_privilege_elevation_of_non_admins,90).

mitigation(upload_a_web_shell_to_a_web_server,apply_latest_patches,90).
mitigation(upload_a_web_shell_to_a_web_server,principle_of_least_privilege,85).

mitigation(data_serialization_external_entities_blowup,tweak_xml_parser_to_not_resolve_external_entities,95).
mitigation(data_serialization_external_entities_blowup,implement_xmlresolver_with_request_timeout,88).
mitigation(data_serialization_external_entities_blowup,tweak_serialized_data_parser_to_not_resolve_external_entities,95).

mitigation(webview_exposure,limit_permission,90).
mitigation(webview_exposure,verify_origion_of_web_content,75).

mitigation(xml_routing_detour_attacks,use_ssl_for_connections_between_all_parties_with_mutual_authentication,50).
mitigation(accessing_intercepting_modifying_http_cookies,use_ssl_tls_to_protect_cookie_in_transit,ensure_the_web_server_implements_all_relevant_security_patches,ensure_the_web_server_implements_all_relevant_security_patches_many_exploitable_buffer_overflows_are_fixed_in_patches_issued_for_the_software,50).

mitigation(subverting_environment_variable_values,protect_environment_variables_against_unauthorized_read_and_write_access,67).
mitigation(subverting_environment_variable_values,protect_the_configuration_files_which_contain_environment_variables_against_illegitimate_read_and_write_access,67).
mitigation(subverting_environment_variable_values,apply_the_least_privilege_principles,67).

mitigation(session_credential_falsification_through_prediction,random_generation_of_session_id,80).
mitigation(session_credential_falsification_through_prediction,adequate_length_of_id,86).
mitigation(session_credential_falsification_through_prediction,session_id_encryption_if_exposed_to_user,91).

mitigation(saas_user_request_forgery,use_secure_proxy_service,94).
mitigation(saas_user_request_forgery,heuristic_analysis_of_behavioral_anomalies,88).

mitigation(session_sidejacking,use_encrypted_secure_channels,85).
mitigation(session_sidejacking,use_vpn,95).
mitigation(session_sidejacking,modify_session_token_with_each_transmission,90).

mitigation(cross_site_tracing,disable_support_for_http_trace,80).
mitigation(cross_site_tracing,patch_web_browser_against_known_exploits,80).

mitigation(reusing_session_ids,invalidate_session_on_logout,95).
mitigation(reusing_session_ids,setup_session_timeout,90).
mitigation(reusing_session_ids,encrypt_session_data_for_given_id,93).
mitigation(reusing_session_ids,multi_factor_authentication,95).

mitigation(session_fixation,strict_session_management_mechanism,90).
mitigation(session_fixation,regenerate_and_destroy_session_identifiers_on_privilege_level_change,75).
mitigation(session_fixation,use_session_identifiers_that_are_hard_to_guess_or_brute_force,91).

mitigation(cross_site_identification,log_out_from_social_networks_when_not_using,90).
mitigation(cross_site_identification,dont_open_other_tabs_while_on_social_networks,50).

mitigation(remote_services_with_stolen_credentials,disable_rdp,50).
mitigation(remote_services_with_stolen_credentials,disable_ssh,50).
mitigation(remote_services_with_stolen_credentials,disable_telnet,50).
mitigation(remote_services_with_stolen_credentials,enable_firewall_rules,50).

mitigation(credential_stuffing,create_a_strong_password_policy,45).
mitigation(credential_stuffing,do_not_reuse_local_administrator_account_credentials_across_systems,45).
mitigation(credential_stuffing,deny_remote_use_of_local_admin_credentials_to_log_into_domain_systems,45).
mitigation(credential_stuffing,do_not_allow_accounts_to_be_a_local_administrator_on_more_than_one_system,45).

mitigation(kerberoasting,monitor_system_and_domain_logs_for_abnormal_access,60).
mitigation(kerberoasting,employ_a_robust_password_policy_for_service_accounts,60).
mitigation(kerberoasting,employ_the_principle_of_least_privilege,60).
mitigation(kerberoasting,enable_aes_kerberos_encryption,60).

mitigation(use_of_captured_tickets,reset_the_built_in_krbtgt_account_password_twice,46).
mitigation(use_of_captured_tickets,monitor_system_and_domain_logs_for_abnormal_access,46).

mitigation(windows_admin_shares_with_stolen_credentials,do_not_reuse_local_administrator_account_credentials_across_systems,50).
mitigation(windows_admin_shares_with_stolen_credentials,deny_remote_use_of_local_admin_credentials_to_log_into_domain_systems,50).
mitigation(windows_admin_shares_with_stolen_credentials,do_not_allow_accounts_to_be_a_local_administrator_on_more_than_one_system,50).

mitigation(use_of_captured_hashes,monitor_system_and_domain_logs_for_abnormal_credential_access,37).
mitigation(use_of_captured_hashes,create_a_strong_password_policy,37).
mitigation(use_of_captured_hashes,apply_patch_kb2871997_to_windows_7_and_higher_systems,37).
mitigation(use_of_captured_hashes,prevent_the_use_of_lan_man_and_nt_lan_man_authentication_on_severs,37).

mitigation(web_services_api_signature_forgery_leveraging_hash_function_extension_weaknes,use_a_secure_message_authentication_code_mac_function_such_as_an_hmac_sha1,70).

mitigation(escaping_a_sandbox_by_calling_code_in_another_language,sanitize_the_code_of_the_standard_libraries_to_make_sure_there_is_no_security_weaknesses_in_them,80).
mitigation(escaping_a_sandbox_by_calling_code_in_another_language,use_obfuscation_and_other_techniques_to_prevent_reverse_engineering_the_standard_libraries,80).
mitigation(escaping_a_sandbox_by_calling_code_in_another_language,use_static_analysis_tool_to_do_code_review_and_dynamic_tool_to_do_penetration_test_on_the_standard_library,80).

mitigation(forceful_browsing,authenticate_request_to_every_resource,56).

mitigation(reflection_attack_in_authentication_protocol,the_server_must_initiate_the_handshake_by_issuing_the_challenge,75).
mitigation(reflection_attack_in_authentication_protocol,the_use_of_hmac_to_hash_the_response_from_the_server_can_also_be_used_to_thwart_reflection,75).

% manipulate timing and state

mitigation(forced_deadlock,use_known_algorithm_to_avoid_deadlock_condition,35).
mitigation(forced_deadlock,use_well_known_libraries_which_implement_synchronization,30).

mitigation(leveraging_race_conditions_via_symbolic_links,use_safe_libraries,45).
mitigation(leveraging_race_conditions_via_symbolic_links,ensure_good_compartmentalization_in_the_system,45).
mitigation(leveraging_race_conditions_via_symbolic_links,ensure_good_compartmentalization_in_the_system,45).

% inject unexpected items

mitigation(using_meta_characters_in_e_mail_headers_to_inject_malicious_payloads,implement_email_filtering_solution_on_mail_server,90).
mitigation(using_meta_characters_in_e_mail_headers_to_inject_malicious_payloads,use_strict_validation_mail_servers,92).

mitigation(format_string_injection,limit_usage_of_formatting_string_functions,85).
mitigation(format_string_injection,strong_imput_validation,90).

mitigation(http_parameter_pollution,use_strict_regular_expressions_in_url_rewriting,88).
mitigation(http_parameter_pollution,attention_on_multiple_occurences_of_parameter_in_a_query_string,75).

mitigation(cross_site_flashing,only_allow_known_url_as_remote_flash_movies_in_flash_application,60).

mitigation(argument_injection,implement_audit_log_written_by_separate_host,70).

mitigation(inclusion_of_code_in_existing_process,use_allow_list_policy,80).
mitigation(inclusion_of_code_in_existing_process,restrict_software_location,40).
mitigation(inclusion_of_code_in_existing_process,monitor_processes_and_command_line_arguments,85).

mitigation(root_jailbreak_detection_evasion_via_hooking,ensure_correct_mobile_application_signin,90).
mitigation(root_jailbreak_detection_evasion_via_hooking,inspect_the_applications_memory_for_suspicious_artifacts,80).
mitigation(root_jailbreak_detection_evasion_via_hooking,inspect_application_stack_trace,85).

mitigation(php_remote_file_inclusion,input_validation,80).
mitigation(php_remote_file_inclusion,allow_only_whitelisted_files,90).

mitigation(cellular_data_injection,commercial_defensive_technology,80).

mitigation(embedding_scripts_within_scripts,use_browser_technology_with_anti_scripting,85).
mitigation(embedding_scripts_within_scripts,input_validation,88).
mitigation(embedding_scripts_within_scripts,output_validation,85).
mitigation(embedding_scripts_within_scripts,session_tokens_for_specific_host,90).

mitigation(overflow_binary_resource_file,perform_bounds_check_on_buffers,80).
mitigation(overflow_binary_resource_file,keep_software_patched,90).

mitigation(using_meta-characters_in_e-mail_headers_to_inject_malicious_payloads,implement_email_filtering_solution_on_mail_server,90).
mitigation(using_meta-characters_in_e-mail_headers_to_inject_malicious_payloads,use_strict_validation_mail_servers,92).

mitigation(generic_cross_browser_cross_domain_theft,perform_proper_html_encoding_and_escaping,88).

mitigation(dom_based_xss,use_browser_technology_with_anti_scripting,90).
mitigation(dom_based_xss,ensure_all_user_supplied_input_is_valid,95).

mitigation(reflected_xss,use_browser_technology_with_anti_scripting,90).
mitigation(reflected_xss,ensure_all_user_supplied_input_is_valid,95).

mitigation(stored_xss,use_browser_technology_with_anti_scripting,90).
mitigation(stored_xss,ensure_all_user_supplied_input_is_valid,95).

mitigation(object_injection,validate_objects_before_deserialization,80).
mitigation(object_injection,keep_session_state_on_the_server,85).

mitigation(ldap_injection,strong_imput_validation,90).
mitigation(ldap_injection,use_of_custom_error_pages,88).

mitigation(dtd_injection,disallow_inclusion_of_dtds,80).
mitigation(dtd_injection,use_xml_parsing_tools_against_dtd_attacks,85).

mitigation(xpath_injection,strong_imput_validation,88).
mitigation(xpath_injection,use_of_parametrized_xpath_queries,90).
mitigation(xpath_injection,use_of_custom_error_pages,80).

mitigation(xquery_injection,run_xml_parsing_and_query_with_minimal_privileges,90).

mitigation(manipulating_writeable_terminal_devices,principle_of_least_privilege,88).

mitigation(command_line_execution_through_sql_injection,disable_mssql_directive,95).
mitigation(command_line_execution_through_sql_injection,data_validation,90).

mitigation(sql_injection_through_soap_parameter_tampering,validate_user_input,75).

mitigation(expanding_control_over_the_operating_system_from_the_database,remove_or_disable_all_unneeded_functions,85).

mitigation(os_command_injection,filter_incoming_data_to_escape_or_remove_characters,77).
mitigation(os_command_injection,run_applications_with_minimal_privilege,87).

mitigation(install_new_service,limit_privilege_of_new_accounts,95).

mitigation(install_rootkit,prevent_adversary_access_to_privileged_accounts,99).

mitigation(replace_file_extension_handlers,inspect_registry_for_changes,70).

mitigation(run_software_at_logon,restrict_write_access_to_logon_scripts,90).

% manipulate data structures

mitigation(relative_path_traversal,input_validation,85).
mitigation(relative_path_traversal,accept_only_known_good,80).
mitigation(relative_path_traversal,use_indirect_references_instead_of_file_names,80).
mitigation(relative_path_traversal,use_permission_on_file_access,90).

mitigation(absolute_path_traversal,input_validation,85).
mitigation(absolute_path_traversal,perform_pen_testing_and_vulnerability_scans,90).
mitigation(absolute_path_traversal,use_indirect_references_instead_of_file_names,80).
mitigation(absolute_path_traversal,use_permission_on_file_access,90).

mitigation(manipulating_web_input_to_file_system_calls,perform_pen_testing_and_vulnerability_scans,90).

mitigation(forced_integer_overflow,use_abstract_libraries_to_abstract_away_risky_apis,20).
mitigation(forced_integer_overflow,bound_checking_before_consuming_input_data,80).

mitigation(double_encoding,refer_to_the_rfcs_to_safely_decode_url,70).
mitigation(double_encoding,use_regular_expressions_to_match_url_patterns,80).

mitigation(using_leading_ghost_character_sequences_to_bypass_input_filters,use_allow_list_policy,80).
mitigation(using_leading_ghost_character_sequences_to_bypass_input_filters,canonicalize_all_data_before_validation,88).

mitigation(using_alternative_ip_address_encodings,input_validation,90).

mitigation(exploiting_multiple_input_interpretation_layers,input_validation,88).
mitigation(exploiting_multiple_input_interpretation_layers,create_an_allow_list,92).

mitigation(embedding_null_bytes,properly_handle_null_values,89).

mitigation(postfix_null_terminate_and_backslash,properly_handle_null_values,89).
mitigation(postfix_null_terminate_and_backslash,create_an_allow_list,89).

mitigation(using_slashes_and_url_encoding_combined_to_bypass_validation_logic,refer_to_the_rfcs_to_safely_decode_url,79).
mitigation(using_slashes_and_url_encoding_combined_to_bypass_validation_logic,regular_expression_can_be_used_to_match_url_patterns,85).

mitigation(using_unicode_encoding_to_bypass_validation_logic,ensure_system_is_unicode_aware,85).
mitigation(using_unicode_encoding_to_bypass_validation_logic,ensure_filtering_and_input_validation_is_canonical,85).
mitigation(using_unicode_encoding_to_bypass_validation_logic,create_an_allow_list,90).

mitigation(buffer_overflow_via_environment_variables,do_not_expose_environment_variable_to_the_user,50).
mitigation(buffer_overflow_via_environment_variables,do_not_use_untrusted_data_in_your_environment_variables,55).
mitigation(buffer_overflow_via_environment_variables,use_a_language_or_compiler_that_performs_automatic_bounds_checking,60).

mitigation(client_side_injection_induced_buffer_overflow,The client software should not install untrusted code from a non-authenticated server,70).
mitigation(client_side_injection_induced_buffer_overflow,perform_input_validation_for_length_of_buffer_inputs,56).
mitigation(client_side_injection_induced_buffer_overflow,ensure_all_buffer_uses_are_consistently_bounds_checked,56).

mitigation(filter_failure_through_buffer_overflow,use_a_language_or_compiler_that_performs_automatic_bounds_checking,40).
mitigation(filter_failure_through_buffer_overflow,use_os_level_preventative_functionality,50).
mitigation(filter_failure_through_buffer_overflow,use_an_abstraction_library_to_abstract_away_risky_apis,50).

mitigation(mime_conversion,stay_up_to_date_with_third_party_vendor_patches,40).
mitigation(mime_conversion,disable_the_7_to_8_bit_conversion,45).
mitigation(mime_conversion,use_the_sendmail_restricted_shell_program,45).

mitigation(overflow_binary_resource_file,perform_appropriate_bounds_checking_on_all_buffers,56).
mitigation(overflow_binary_resource_file,enforce_principle_of_least_privilege,58).
mitigation(overflow_binary_resource_file,static_code_analysis,59).


mitigation(buffer_overflow_via_symbolic_links,pay_attention_to_the_resource_pointed_to_by_your_symlink_links,56).
mitigation(buffer_overflow_via_symbolic_links,always_check_the_size_of_the_input_data_before_copying_to_a_buffer,60).
mitigation(buffer_overflow_via_symbolic_links,use_a_language_or_compiler_that_performs_automatic_bounds_checking,70).


mitigation(overflow_variables_and_tags,use_a_language_or_compiler_that_performs_automatic_bounds_checking,40).
mitigation(overflow_variables_and_tags,use_an_abstraction_library_to_abstract_away_risky_apis,40).
mitigation(overflow_variables_and_tags,use_os_level_preventative_functionality,40).

mitigation(buffer_overflow_via_parameter_expansion,ensure_that_when_parameter_expansion_happens_in_the_code,50).

mitigation(string_format_overflow_in_syslog,the_code_should_be_reviewed_for_misuse_of_the_syslog_function_call,60).

mitigation(buffer_overflow_in_an_api_call,use_a_language_or_compiler_that_performs_automatic_bounds_checking,78).
mitigation(buffer_overflow_in_an_api_call,use_secure_functions_not_vulnerable_to_buffer_overflow,77).
mitigation(buffer_overflow_in_an_api_call,if_you_have_to_use_dangerous_functions,_make_sure_that_you_do_boundary_checking,90).

mitigation(buffer_overflow_in_local_command_line_utilities,use_a_language_or_compiler_that_performs_automatic_bounds_checking,60).
mitigation(buffer_overflow_in_local_command_line_utilities,use_an_abstraction_library_to_abstract_away_risky_apis,60).
mitigation(buffer_overflow_in_local_command_line_utilities,use_os_level_preventative_functionality,60).