% mitigation(attack,mitigation,percentage)

% employ probabilistic techniques
mitigation(fuzzing_for_application_mapping,['obfuscate_server_fields_of_http_response','hide_inner_ordering_of_http_response_header','customizing_http_error_codes','hide_http_response_information','hide_cookies']).

mitigation(encryption_brute_forcing,['use_commonly_accepted_algorithms','moores_law']).

mitigation(dictionary-based_password_attack,['create_strong_passwords','implement_intelligent_password_throttling_mechanism','multi_factor_authentication']).

mitigation(rainbow_table_password_cracking,['use_salt_when_hashing_passwords']).

mitigation(password_spraying,['create_strong_passwords','implement_intelligent_password_throttling_mechanism','multi_factor_authentication']).

mitigation(try_common_or_default_usernames_and_passwords,['delete_default_account_credentials','implement_intelligent_password_throttling_mechanism','create_strong_passwords','password_recycling']).

% subvert access control

mitigation(cross_zone_scripting,['disable_script_execution','input_validation','ensure_proper_html_output']).

mitigation(catching_exception_throw_signal_from_privileged_block,['careful_desing_of_callback_signal_and_other_asynchronous_constructs','careful_desing_of_privileged_code_blocks']).

mitigation(target_programs_with_elevated_privileges,['principle_of_least_privilege','validate_untrusted_data','apply_latest_patches','protect_logs_from_log_forging','traffic_and_resource_usage_monitoring']).

mitigation(restful_privilege_elevation,['ensure_get_methods_only_retrieve_state']).

mitigation(modify_shared_file,['disallow_shared_content','minimize_users_with_shared_access']).

mitigation(add_malicious_file_to_shared_webroot,['ensure_permission_on_accessible_directories','disallow_remote_access','disable_execution_on_directories_withing_web_root']).

mitigation(replace_binaries,['ensure_commonly_used_binaries_have_correct_permission','restrict_privilege_elevation_of_non_admins']).

mitigation(upload_a_web_shell_to_a_web_server,['apply_latest_patches','principle_of_least_privilege']).

mitigation(data_serialization_external_entities_blowup,['tweak_xml_parser_to_not_resolve_external_entities','implement_xmlresolver_with_request_timeout','tweak_serialized_data_parser_to_not_resolve_external_entities']).

mitigation(webview_exposure,['limit_permission','verify_origion_of_web_content']).

mitigation(xml_routing_detour_attacks,['use_ssl_for_connections_between_all_parties_with_mutual_authentication']).

mitigation(accessing_intercepting_modifying_http_cookies,['use_ssl_tls_to_protect_cookie_in_transit','ensure_the_web_server_implements_all_relevant_security_patches']).

mitigation(subverting_environment_variable_values,['protect_environment_variables_against_unauthorized_read_and_write_access','protect_the_configuration_files_which_contain_environment_variables_against_illegitimate_read_and_write_access','apply_the_least_privilege_principles']).

mitigation(session_credential_falsification_through_prediction,['random_generation_of_session_id','adequate_length_of_id','session_id_encryption_if_exposed_to_user']).

mitigation(saas_user_request_forgery,['use_secure_proxy_service','heuristic_analysis_of_behavioral_anomalies']).

mitigation(session_sidejacking,['use_encrypted_secure_channels','use_vpn','modify_session_token_with_each_transmission']).

mitigation(cross_site_tracing,['disable_support_for_http_trace','patch_web_browser_against_known_exploits']).

mitigation(reusing_session_ids,['invalidate_session_on_logout','setup_session_timeout','encrypt_session_data_for_given_id','multi_factor_authentication']).

mitigation(session_fixation,['strict_session_management_mechanism','regenerate_and_destroy_session_identifiers_on_privilege_level_change','use_session_identifiers_that_are_hard_to_guess_or_brute_force']).

mitigation(cross_site_identification,['log_out_from_social_networks_when_not_using','dont_open_other_tabs_while_on_social_networks']).

mitigation(remote_services_with_stolen_credentials,['disable_rdp','disable_ssh','disable_telnet','enable_firewall_rules']).

mitigation(credential_stuffing,['create_a_strong_password_policy','do_not_reuse_local_administrator_account_credentials_across_systems','deny_remote_use_of_local_admin_credentials_to_log_into_domain_systems','do_not_allow_accounts_to_be_a_local_administrator_on_more_than_one_system']).

mitigation(kerberoasting,['monitor_system_and_domain_logs_for_abnormal_access','employ_a_robust_password_policy_for_service_accounts','employ_the_principle_of_least_privilege','enable_aes_kerberos_encryption']).

mitigation(use_of_captured_tickets,['reset_the_built_in_krbtgt_account_password_twice','monitor_system_and_domain_logs_for_abnormal_access']).

mitigation(windows_admin_shares_with_stolen_credentials,['do_not_reuse_local_administrator_account_credentials_across_systems','deny_remote_use_of_local_admin_credentials_to_log_into_domain_systems','do_not_allow_accounts_to_be_a_local_administrator_on_more_than_one_system']).

mitigation(use_of_captured_hashes,['monitor_system_and_domain_logs_for_abnormal_credential_access','create_a_strong_password_policy','apply_patch_kb2871997_to_windows_7_and_higher_systems','prevent_the_use_of_lan_man_and_nt_lan_man_authentication_on_severs']).

mitigation(web_services_api_signature_forgery_leveraging_hash_function_extension_weaknes,['use_a_secure_message_authentication_code_mac_function_such_as_an_hmac_sha1']).

mitigation(escaping_a_sandbox_by_calling_code_in_another_language,['sanitize_the_code_of_the_standard_libraries_to_make_sure_there_is_no_security_weaknesses_in_them','use_obfuscation_and_other_techniques_to_prevent_reverse_engineering_the_standard_libraries','use_static_analysis_tool_to_do_code_review_and_dynamic_tool_to_do_penetration_test_on_the_standard_library']).

mitigation(forceful_browsing,['authenticate_request_to_every_resource']).

mitigation(reflection_attack_in_authentication_protocol,['the_server_must_initiate_the_handshake_by_issuing_the_challenge','the_use_of_hmac_to_hash_the_response_from_the_server_can_also_be_used_to_thwart_reflection']).

% manipulate timing and state

mitigation(forced_deadlock,['use_known_algorithm_to_avoid_deadlock_condition', 'use_well_known_libraries_which_implement_synchronization']).

mitigation(leveraging_race_conditions_via_symbolic_links,['use_safe_libraries', 'ensure_good_compartmentalization_in_the_system']).

% inject unexpected items

mitigation(using_meta_characters_in_e_mail_headers_to_inject_malicious_payloads,['implement_email_filtering_solution_on_mail_server','use_strict_validation_mail_servers']).

mitigation(format_string_injection,['limit_usage_of_formatting_string_functions','strong_input_validation']).

mitigation(http_parameter_pollution,['use_strict_regular_expressions_in_url_rewriting','attention_on_multiple_occurences_of_parameter_in_a_query_string']).

mitigation(cross_site_flashing,['only_allow_known_url_as_remote_flash_movies_in_flash_application']).

mitigation(argument_injection,['implement_audit_log_written_by_separate_host']).

mitigation(inclusion_of_code_in_existing_process,['use_allow_list_policy', 'restrict_software_location', 'monitor_processes_and_command_line_arguments']).

mitigation(root_jailbreak_detection_evasion_via_hooking,['ensure_correct_mobile_application_signin', 'inspect_the_applications_memory_for_suspicious_artifacts', 'inspect_application_stack_trace']).

mitigation(php_remote_file_inclusion,['input_validation', 'allow_only_whitelisted_files']).

mitigation(cellular_data_injection,['commercial_defensive_technology']).

mitigation(embedding_scripts_within_scripts,['use_browser_technology_with_anti_scripting', 'input_validation', 'output_validation', 'session_tokens_for_specific_host']).

mitigation(overflow_binary_resource_file,['perform_bounds_check_on_buffers', 'keep_software_patched']).

mitigation(using_meta-characters_in_e-mail_headers_to_inject_malicious_payloads,['implement_email_filtering_solution_on_mail_server', 'use_strict_validation_mail_servers']).

mitigation(generic_cross_browser_cross_domain_theft,['perform_proper_html_encoding_and_escaping']).

mitigation(dom_based_xss,['use_browser_technology_with_anti_scripting', 'ensure_all_user_supplied_input_is_valid']).

mitigation(reflected_xss,['use_browser_technology_with_anti_scripting', 'ensure_all_user_supplied_input_is_valid']).

mitigation(stored_xss,['use_browser_technology_with_anti_scripting', 'ensure_all_user_supplied_input_is_valid']).

mitigation(object_injection,['validate_objects_before_deserialization', 'keep_session_state_on_the_server']).

mitigation(ldap_injection,['strong_input_validation', 'use_of_custom_error_pages']).

mitigation(dtd_injection,['disallow_inclusion_of_dtds', 'use_xml_parsing_tools_against_dtd_attacks']).

mitigation(xpath_injection,['strong_input_validation', 'use_of_parametrized_xpath_queries', 'use_of_custom_error_pages']).

mitigation(xquery_injection,['run_xml_parsing_and_query_with_minimal_privileges']).

mitigation(manipulating_writeable_terminal_devices,['principle_of_least_privilege']).

mitigation(command_line_execution_through_sql_injection,['disable_mssql_directive', 'data_validation']).

mitigation(sql_injection_through_soap_parameter_tampering,['validate_user_input']).

mitigation(expanding_control_over_the_operating_system_from_the_database,['remove_or_disable_all_unneeded_functions']).

mitigation(os_command_injection,['filter_incoming_data_to_escape_or_remove_characters', 'run_applications_with_minimal_privilege']).

mitigation(install_new_service,['limit_privilege_of_new_accounts']).

mitigation(install_rootkit,['prevent_adversary_access_to_privileged_accounts']).

mitigation(replace_file_extension_handlers,['inspect_registry_for_changes']).

mitigation(run_software_at_logon,['restrict_write_access_to_logon_scripts']).

% manipulate data structures

mitigation(relative_path_traversal,['input_validation','accept_only_known_good','use_indirect_references_instead_of_file_names','use_permission_on_file_access']).

mitigation(absolute_path_traversal,['input_validation','perform_pen_testing_and_vulnerability_scans','use_indirect_references_instead_of_file_names','use_permission_on_file_access']).

mitigation(manipulating_web_input_to_file_system_calls,['perform_pen_testing_and_vulnerability_scans']).

mitigation(forced_integer_overflow,['use_abstract_libraries_to_abstract_away_risky_apis','bound_checking_before_consuming_input_data']).

mitigation(double_encoding,['refer_to_the_rfcs_to_safely_decode_url','use_regular_expressions_to_match_url_patterns']).

mitigation(using_leading_ghost_character_sequences_to_bypass_input_filters,['use_allow_list_policy','canonicalize_all_data_before_validation']).

mitigation(using_alternative_ip_address_encodings,['input_validation']).

mitigation(exploiting_multiple_input_interpretation_layers,['input_validation','create_an_allow_list']).

mitigation(embedding_null_bytes,['properly_handle_null_values']).

mitigation(postfix_null_terminate_and_backslash,['properly_handle_null_values','create_an_allow_list']).

mitigation(using_slashes_and_url_encoding_combined_to_bypass_validation_logic,['refer_to_the_rfcs_to_safely_decode_url','regular_expression_can_be_used_to_match_url_patterns']).

mitigation(using_unicode_encoding_to_bypass_validation_logic,['ensure_system_is_unicode_aware','ensure_filtering_and_input_validation_is_canonical','create_an_allow_list']).

mitigation(buffer_overflow_via_environment_variables,['do_not_expose_environment_variable_to_the_user','do_not_use_untrusted_data_in_your_environment_variables','use_a_language_or_compiler_that_performs_automatic_bounds_checking']).

mitigation(client_side_injection_induced_buffer_overflow,['the_client_software_should_not_install_untrusted_code_from_a_non_authenticated_server','perform_input_validation_for_length_of_buffer_inputs','ensure_all_buffer_uses_are_consistently_bounds_checked']).

mitigation(filter_failure_through_buffer_overflow,['use_a_language_or_compiler_that_performs_automatic_bounds_checking','use_os_level_preventative_functionality','use_an_abstraction_library_to_abstract_away_risky_apis']).

mitigation(mime_conversion,['stay_up_to_date_with_third_party_vendor_patches','disable_the_7_to_8_bit_conversion','use_the_sendmail_restricted_shell_program']).

mitigation(overflow_binary_resource_file,['perform_appropriate_bounds_checking_on_all_buffers','enforce_principle_of_least_privilege','static_code_analysis']).

mitigation(buffer_overflow_via_symbolic_links,['pay_attention_to_the_resource_pointed_to_by_your_symlink_links','always_check_the_size_of_the_input_data_before_copying_to_a_buffer','use_a_language_or_compiler_that_performs_automatic_bounds_checking']).

mitigation(overflow_variables_and_tags, ['use_a_language_or_compiler_that_performs_automatic_bounds_checking', 'use_an_abstraction_library_to_abstract_away_risky_apis', 'use_os_level_preventative_functionality']).

mitigation(buffer_overflow_via_parameter_expansion,['ensure_that_when_parameter_expansion_happens_in_the_code']).

mitigation(string_format_overflow_in_syslog,['the_code_should_be_reviewed_for_misuse_of_the_syslog_function_call']).

mitigation(buffer_overflow_in_an_api_call, ['use_a_language_or_compiler_that_performs_automatic_bounds_checking', 'use_secure_functions_not_vulnerable_to_buffer_overflow', 'make_sure_that_you_do_boundary_checking']).

mitigation(buffer_overflow_in_local_command_line_utilities, ['use_a_language_or_compiler_that_performs_automatic_bounds_checking',  'use_an_abstraction_library_to_abstract_away_risky_apis', 'use_os_level_preventative_functionality']).