%(attack,weakness,percentage)

attack(cross_zone_scripting).
attributes(cross_zone_scripting, [104, medium, high]).
weakness(cross_zone_scripting,execution_with_unnecessary_privileges,1).
weakness(cross_zone_scripting,not_using_complete_mediation,1).
weakness(cross_zone_scripting,improper_authorization,1).
weakness(cross_zone_scripting,improper_encoding_or_escaping_of_output,1).
weakness(cross_zone_scripting,improper_input_validation,1).

attack(hijacking_a_privileged_process).
attributes(hijacking_a_privileged_process, [234, null, medium]).
weakness(hijacking_a_privileged_process,incorrect_permission_assignment_for_critical_resource,1).
weakness(hijacking_a_privileged_process,incorrect_use_of_privileged_apis,1).

attack(catching_exception_throw_signal_from_privileged_block).
attributes(catching_exception_throw_signal_from_privileged_block, [236, low, very_high]).
weakness(catching_exception_throw_signal_from_privileged_block,privilege_context_switching_error,1).

attack(signing_malicious_code).
attributes(signing_malicious_code, [206, null, very_high]).
weakness(signing_malicious_code,incorrect_permission_assignment_for_critical_resource,1).

attack(target_programs_with_elevated_privileges).
attributes(target_programs_with_elevated_privileges, [69, high, very_high]).
weakness(target_programs_with_elevated_privileges,execution_with_unnecessary_privileges,1).
weakness(target_programs_with_elevated_privileges,permissions_privileges_and_access_controls,1).
weakness(target_programs_with_elevated_privileges,external_control_of_system_or_configuration_setting,1).

attack(restful_privilege_elevation).
attributes(restful_privilege_elevation, [58, high, high]).
weakness(restful_privilege_elevation,privilege_defined_with_unsafe_actions,1).
weakness(restful_privilege_elevation,improper_privilege_management,1).
weakness(restful_privilege_elevation,permissions_privileges_and_access_controls,1).

attack(create_files_with_the_same_name_as_files_protected_with_a_higher_classification).
attributes(create_files_with_the_same_name_as_files_protected_with_a_higher_classification, [177, null, very_high]).
weakness(create_files_with_the_same_name_as_files_protected_with_a_higher_classification,use_of_incorrectly-resolved_name_or_reference,1).

attack(force_use_of_corrupted_files).
attributes(force_use_of_corrupted_files, [263, null, medium]).
weakness(force_use_of_corrupted_files,inclusion_of_functionality_from_untrusted_control_sphere,1).

attack(modify_shared_file).
attributes(modify_shared_file, [562, null, null]).
weakness(modify_shared_file,improper_access_control,1).

attack(add_malicious_file_to_shared_webroot).
attributes(add_malicious_file_to_shared_webroot, [563, null, null]).
weakness(add_malicious_file_to_shared_webroot,improper_access_control,1).

attack(replace_binaries).
attributes(replace_binaries, [642, null, high]).
weakness(replace_binaries,incorrect_permission_assignment_for_critical_resource,1).

attack(upload_a_web_shell_to_a_web_server).
attributes(upload_a_web_shell_to_a_web_server, [650, null, high]).
weakness(upload_a_web_shell_to_a_web_server,improper_authentication,1).
weakness(upload_a_web_shell_to_a_web_server,command_shell_in_externally_accessible_directory,1).

attack(data_serialization_external_entities_blowup).
attributes(data_serialization_external_entities_blowup, [221, null, null]).
weakness(data_serialization_external_entities_blowup,improper_restriction_of_xml_external_entity_reference,1).

attack(webview_exposure).
attributes(webview_exposure, [503, null, null]).
weakness(webview_exposure,improper_access_control,1).

attack(xml_routing_detour_attacks).
attributes(xml_routing_detour_attacks, [219, high, medium]).
weakness(xml_routing_detour_attacks,unintended_proxy_or_intermediary,1).
weakness(xml_routing_detour_attacks,externally_controlled_reference_to_a_resource_in_another_sphere,1).	

attack(transaction_or_event_tampering_via_application_api_manipulation).
attributes(transaction_or_event_tampering_via_application_api_manipulation, [385, null, medium]).
weakness(transaction_or_event_tampering_via_application_api_manipulation,modification_of_assumed_immutable_data,1).
weakness(transaction_or_event_tampering_via_application_api_manipulation,insufficient_verification_of_data_authenticity,1).
weakness(transaction_or_event_tampering_via_application_api_manipulation,origin_validation_error,1).
weakness(transaction_or_event_tampering_via_application_api_manipulation,client_side_enforcement_of_server_side_security,1).
weakness(transaction_or_event_tampering_via_application_api_manipulation,missing_encryption_of_sensitive_data,1).

attack(content_spoofing_via_application_api_manipulation).
attributes(content_spoofing_via_application_api_manipulation, [389, null, low]).
weakness(content_spoofing_via_application_api_manipulation,missing_support_for_integrity_check,1).

attack(navigation_remapping_to_propagate_malicious_content).
attributes(navigation_remapping_to_propagate_malicious_content, [387, null, medium]).
weakness(navigation_remapping_to_propagate_malicious_content,modification_of_assumed_immutable_data,1).
weakness(navigation_remapping_to_propagate_malicious_content,insufficient_verification_of_data_authenticity,1).
weakness(navigation_remapping_to_propagate_malicious_content,origin_validation_error,1).
weakness(navigation_remapping_to_propagate_malicious_content,client_side_enforcement_of_server_side_security,1).
weakness(navigation_remapping_to_propagate_malicious_content,missing_encryption_of_sensitive_data,1).

attack(application_api_button_hijacking).
attributes(application_api_button_hijacking, [388, null, medium]).
weakness(application_api_button_hijacking,modification_of_assumed_immutable_data,1).
weakness(application_api_button_hijacking,insufficient_verification_of_data_authenticity,1).
weakness(application_api_button_hijacking,origin_validation_error,1).
weakness(application_api_button_hijacking,client_side_enforcement_of_server_side_security,1).
weakness(application_api_button_hijacking,missing_encryption_of_sensitive_data,1).

attack(leveraging_active_man_in_the_middle_attacks_to_bypass_same_origin_policy).
attributes(leveraging_active_man_in_the_middle_attacks_to_bypass_same_origin_policy, [466, null, medium]).
weakness(leveraging_active_man_in_the_middle_attacks_to_bypass_same_origin_policy,channel_accessible_by_non-endpoint,1).

attack(reflection_attack_in_authentication_protocol).
attributes(reflection_attack_in_authentication_protocol, [90, high, high]).
weakness(reflection_attack_in_authentication_protocol,reflection_attack_in_an_authentication_protocol,1).
weakness(reflection_attack_in_authentication_protocol,incorrect_implementation_of_authentication_algorithm,1).
weakness(reflection_attack_in_authentication_protocol,owasp_top_ten_2007_category_a7_broken_authentication_and_session_management,1).

attack(web_services_api_signature_forgery_leveraging_hash_function_extension_weakness).
attributes(web_services_api_signature_forgery_leveraging_hash_function_extension_weakness, [461, null, high]).
weakness(web_services_api_signature_forgery_leveraging_hash_function_extension_weakness,reversible_one_way_hash,1).
weakness(web_services_api_signature_forgery_leveraging_hash_function_extension_weakness,authentication_bypass_by_spoofing,1).

attack(escaping_a_sandbox_by_calling_code_in_another_language).
attributes(escaping_a_sandbox_by_calling_code_in_another_language, [237, low, very_high]).
weakness(escaping_a_sandbox_by_calling_code_in_another_language,protection_mechanism_failure,1).

attack(forceful_browsing).
attributes(forceful_browsing, [87, high, high]).
weakness(forceful_browsing,direct_request,1).
weakness(forceful_browsing,improper_authorization,1).
weakness(forceful_browsing,protection_mechanism_failure,1).

attack(create_malicious_client).
attributes(create_malicious_client, [202, null, medium]).
weakness(create_malicious_client,client_side_enforcement_of_server_side_security,1).

attack(accessing_intercepting_modifying_http_cookies).
attributes(accessing_intercepting_modifying_http_cookies, [31, high, high]).
weakness(accessing_intercepting_modifying_http_cookies,reliance_on_cookies_without_validation_and_integrity_checking,1).
weakness(accessing_intercepting_modifying_http_cookies,authentication_bypass_by_assumed_immutable_data,1).
weakness(accessing_intercepting_modifying_http_cookies,missing_encryption_of_sensitive_data,1).
weakness(accessing_intercepting_modifying_http_cookies,improper_neutralization_of_crlf_sequences_in_http_headers,1).
weakness(accessing_intercepting_modifying_http_cookies,use_of_persistent_cookies_containing_sensitive_information,1).
weakness(accessing_intercepting_modifying_http_cookies,improper_input_validation,1).
weakness(accessing_intercepting_modifying_http_cookies,cleartext_storage_of_sensitive_information_in_a_cookie,1).
weakness(accessing_intercepting_modifying_http_cookies,session_fixation,1).
weakness(accessing_intercepting_modifying_http_cookies,external_control_of_assumed_immutable_web_parameter,1).
weakness(accessing_intercepting_modifying_http_cookies,owasp_top_ten_2004_category_a3_broken_authentication_and_session_management,1).
weakness(accessing_intercepting_modifying_http_cookies,client_side_enforcement_of_server_side_security,1).
weakness(accessing_intercepting_modifying_http_cookies,external_control_of_critical_state_data,1).

attack(subverting_environment_variable_values).
attributes(subverting_environment_variable_values, [13, high, very_high]).
weakness(subverting_environment_variable_values,missing_support_for_integrity_check,1).
weakness(subverting_environment_variable_values,improper_authorization,1).
weakness(subverting_environment_variable_values,authentication_bypass_by_assumed_immutable_data,1).
weakness(subverting_environment_variable_values,improper_neutralization_of_special_elements_in_output_used_by_a_downstream_component,1).
weakness(subverting_environment_variable_values,external_control_of_system_or_configuration_setting,1).
weakness(subverting_environment_variable_values,external_control_of_file_name_or_path,1).
weakness(subverting_environment_variable_values,improper_input_validation,1).
weakness(subverting_environment_variable_values,exposure_of_sensitive_information_to_an_unauthorized_actor,1).

attack(manipulating_hidden_fields).
attributes(manipulating_hidden_fields, [162, null, high]).
weakness(manipulating_hidden_fields,client_side_enforcement_of_server_side_security,1).
weakness(use_of_captured_hashes_(pass_the_hash),insufficiently_protected_credentials,1).
weakness(use_of_captured_hashes_(pass_the_hash),use_of_password_hash_instead_of_password_for_authentication,1).
weakness(use_of_captured_hashes_(pass_the_hash),use_of_single_factor_authentication,1).
weakness(use_of_captured_hashes_(pass_the_hash),authentication_bypass_by_capture_replay,1).
weakness(use_of_captured_hashes_(pass_the_hash),use_of_single_factor_authentication,1).

attack(windows_admin_shares_with_stolen_credentials).
attributes(windows_admin_shares_with_stolen_credentials, [561, null, null]).
weakness(windows_admin_shares_with_stolen_credentials,insufficiently_protected_credentials,1).
weakness(windows_admin_shares_with_stolen_credentials,use_of_single_factor_authentication,1).
weakness(windows_admin_shares_with_stolen_credentials,use_of_password_system_for_primary_authentication,1).
weakness(windows_admin_shares_with_stolen_credentials,authentication_bypass_by_capture_replay,1).
weakness(windows_admin_shares_with_stolen_credentials,password_aging_with_long_expiration,1).
weakness(windows_admin_shares_with_stolen_credentials,not_using_password_aging,1).
weakness(windows_admin_shares_with_stolen_credentials,weak_password_requirements,1).

attack(use_of_captured_tickets).
attributes(use_of_captured_tickets, [645, low, high]).
weakness(use_of_captured_tickets,insufficiently_protected_credentials,1).
weakness(use_of_captured_tickets,authentication_bypass_by_capture_replay,1).
weakness(use_of_captured_tickets,use_of_single-factor_authentication,1).

attack(kerberoasting).
attributes(kerberoasting, [509, null, high]).
weakness(kerberoasting,insufficiently_protected_credentials,1).
weakness(kerberoasting,use_of_single_factor_authentication,1).
weakness(kerberoasting,use_of_password_system_for_primary_authentication,1).
weakness(kerberoasting,authentication_bypass_by_capture_replay,1).
weakness(kerberoasting,password_aging_with_long_expiration,1).
weakness(kerberoasting,not_using_password_aging,1).
weakness(kerberoasting,weak_password_requirements,1).

attack(credential_stuffing).
attributes(credential_stuffing, [600, high, high]).
weakness(credential_stuffing,insufficiently_protected_credentials,1).
weakness(credential_stuffing,improper_restriction_of_excessive_authentication_attempts,1).
weakness(credential_stuffing,use_of_single_factor_authentication,1).
weakness(credential_stuffing,use_of_password_system_for_primary_authentication,1).
weakness(credential_stuffing,not_using_password_aging,1).
weakness(credential_stuffing,password_aging_with_long_expiration,1).
weakness(credential_stuffing,reliance_on_a_single_factor_in_a_security_decision,1).

attack(remote_services_with_stolen_credentials).
attributes(remote_services_with_stolen_credentials, [555, null, very_high]).
weakness(remote_services_with_stolen_credentials,insufficiently_protected_credentials,1).
weakness(remote_services_with_stolen_credentials,use_of_single_factor_authentication,1).
weakness(remote_services_with_stolen_credentials,use_of_password_system_for_primary_authentication,1).
weakness(remote_services_with_stolen_credentials,authentication_bypass_by_capture_replay,1).
weakness(remote_services_with_stolen_credentials,password_aging_with_long_expiration,1).
weakness(remote_services_with_stolen_credentials,not_using_password_aging,1).
weakness(remote_services_with_stolen_credentials,weak_password_requirements,1).

attack(session_credential_falsification_through_manipulation).
attributes(session_credential_falsification_through_manipulation, [226, null, medium]).
weakness(session_credential_falsification_through_manipulation,reliance_on_cookies_without_validation_and_integrity_checking,1).
weakness(session_credential_falsification_through_manipulation,external_control_of_assumed_immutable_web_parameter,1).


attack(session_credential_falsification_through_prediction).
attributes(session_credential_falsification_through_prediction, [59, high, high]).
weakness(session_credential_falsification_through_prediction,authentication_bypass_by_spoofing,1).
weakness(session_credential_falsification_through_prediction,use_of_insufficiently_random_values,1).
weakness(session_credential_falsification_through_prediction,insufficient_entropy,1).
weakness(session_credential_falsification_through_prediction,origin_validation_error,1).
weakness(session_credential_falsification_through_prediction,exposure_of_data_element_to_wrong_session,1).
weakness(session_credential_falsification_through_prediction,use_of_persistent_cookies_containing_sensitive_information,1).
weakness(session_credential_falsification_through_prediction,exposure_of_sensitive_information_to_an_unauthorized_actor,1).
weakness(session_credential_falsification_through_prediction,j2ee_misconfiguration:_insufficient_session_id_length,1).
weakness(session_credential_falsification_through_prediction,improper_authorization,1).
weakness(session_credential_falsification_through_prediction,session_fixation,1).
weakness(session_credential_falsification_through_prediction,protection_mechanism_failure,1).
weakness(session_credential_falsification_through_prediction,owasp_top_ten_2007_category_a8_insecure_cryptographic_storage,1).

attack(saas_user_request_forgery).
attributes(saas_user_request_forgery, [510, high, medium]).
weakness(saas_user_request_forgery,origin_validation_error,1).

attack(session_sidejacking).
attributes(session_sidejacking, [102, high, high]).
weakness(session_sidejacking,authentication_bypass_by_capture_replay,1).
weakness(session_sidejacking,insufficiently_protected_credentials,1).
weakness(session_sidejacking,unprotected_transport_of_credentials,1).
weakness(session_sidejacking,cleartext_transmission_of_sensitive_information,1).
weakness(session_sidejacking,sensitive_cookie_in_https_session_without_secure_attribute,1).

attack(cross_site_tracing).
attributes(cross_site_tracing, [107, medium, very_high]).
weakness(cross_site_tracing,protection_mechanism_failure,1).
weakness(cross_site_tracing,incorrect_use_of_privileged_apis,1).

attack(reusing_session_ids).
attributes(reusing_session_ids, [60, high, high]).
weakness(reusing_session_ids,authentication_bypass_by_capture_replay,1).
weakness(reusing_session_ids,authentication_bypass_by_spoofing,1).
weakness(reusing_session_ids,origin_validation_error,1).
weakness(reusing_session_ids,session_fixation,1).
weakness(reusing_session_ids,exposure_of_data_element_to_wrong_session,1).
weakness(reusing_session_ids,use_of_persistent_cookies_containing_sensitive_information,1).
weakness(reusing_session_ids,exposure_of_sensitive_information_to_an_unauthorized_actor,1).
weakness(reusing_session_ids,improper_authorization,1).
weakness(reusing_session_ids,improper_control_of_a_resource_through_its_lifetime,1).
weakness(reusing_session_ids,incorrect_permission_assignment_for_critical_resource,1).

attack(session_fixation).
attributes(session_fixation, [61, medium, high]).
weakness(session_fixation,session_fixation,1).
weakness(session_fixation,7pk_time_and_state,1).
weakness(session_fixation,improper_control_of_a_resource_through_its_lifetime,1).
weakness(session_fixation,incorrect_permission_assignment_for_critical_resource,1).

attack(cross_site_identification).
attributes(cross_site_identification, [467, null, low]).
weakness(cross_site_identification,cross_site_request_forgery,1).
weakness(cross_site_identification,exposure_of_private_personal_information_to_an_unauthorized_actor,1).